import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Header from '../components/Header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <small>I&rsquo;m a </small>
        <strong>Digital Designer <span className={styles.highlight}>/</span><br /> Creative Developer</strong>

        <small>I&rsquo;m on</small>
        <strong>
          <a href="https://dribbble.com/stevenorell" target="_blank" rel="noreferrer">Dribbble</a>&nbsp;<span className={styles.highlight}>/</span>&nbsp;
          <a href="https://github.com/stevenorell" target="_blank" rel="noreferrer">Github</a>&nbsp;<span className={styles.highlight}>/</span>&nbsp;
          <a href="https://medium.com/@stevenorell" target="_blank" rel="noreferrer">Medium</a>
        </strong>
      </main>
    </div>
  )
}
